# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-Plugin-QRCode
version:      0.01
version_from: lib/Sledge/Plugin/QRCode.pm
installdirs:  site
requires:
    GD::Barcode:                   1.15
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
